openapi: 3.0.0
info:
  title: Svelte.rs
  version: 0.1.27
servers:
- url: http://localhost:3000
tags:
- name: Demo
- name: Users
paths:
  /demo/hello_from_rust:
    get:
      tags:
      - Demo
      summary: Hello world
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                type: string
  /users:
    get:
      tags:
      - Users
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
      security:
      - BearerToken: []
  /users/{user_id}:
    get:
      tags:
      - Users
      parameters:
      - name: user_id
        schema:
          type: string
          format: uuid
        in: path
        required: true
        deprecated: false
        explode: true
        style: null
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/User'
      security:
      - BearerToken: []
  /auth/user:
    get:
      tags:
      - Users
      summary: Gets the current user
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/User'
      security:
      - BearerToken: []
  /auth/register:
    post:
      tags:
      - Users
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              $ref: '#/components/schemas/RegisterUser'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/AuthResponse'
components:
  schemas:
    AuthResponse:
      type: object
      title: AuthResponse
      required:
      - message
      - token
      properties:
        message:
          type: string
        token:
          type: string
    RegisterUser:
      type: object
      title: RegisterUser
      required:
      - email
      - password
      properties:
        email:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        password:
          type: string
    User:
      type: object
      title: User
      required:
      - id
      - role
      - email
      - is_active
      - created_at
      - updated_at
      properties:
        id:
          type: string
          format: uuid
        role:
          $ref: '#/components/schemas/UserRole'
        email:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    UserRole:
      type: string
      enum:
      - Admin
      - Moderator
      - User
  securitySchemes:
    BearerToken:
      type: http
      scheme: bearer
