openapi: 3.0.0
info:
  title: Svelte.rs
  version: 0.1.21
servers:
- url: http://localhost:3000
tags: []
paths:
  /:
    get:
      summary: Hello world
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                type: string
  /echo:
    post:
      summary: Echo
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                type: string
  /customer/:customer_id:
    get:
      parameters:
      - name: customer_id
        schema:
          type: string
        in: path
        required: true
        deprecated: false
        explode: true
        style: null
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                type: string
components:
  schemas: {}
