// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetData, GetResponse, GetEchoData, GetEchoResponse, GetCustomerCustomerIdData, GetCustomerCustomerIdResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Hello world
 */
export const get = <ThrowOnError extends boolean = false>(options?: Options<GetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetResponse, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * Echo
 */
export const getEcho = <ThrowOnError extends boolean = false>(options: Options<GetEchoData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetEchoResponse, unknown, ThrowOnError>({
        url: '/echo',
        ...options,
        headers: {
            'Content-Type': 'application/json; charset=utf-8',
            ...options?.headers
        }
    });
};

export const getCustomerCustomerId = <ThrowOnError extends boolean = false>(options: Options<GetCustomerCustomerIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCustomerCustomerIdResponse, unknown, ThrowOnError>({
        url: '/customer/:customer_id',
        ...options
    });
};