// This file is auto-generated by @hey-api/openapi-ts

export type RegisterUser = {
    email: string;
    first_name?: string;
    last_name?: string;
    password: string;
};

export type User = {
    id: string;
    email: string;
    first_name?: string;
    last_name?: string;
    is_active: boolean;
    created_at: string;
    updated_at: string;
};

export type GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetResponses = {
    200: string;
};

export type GetResponse = GetResponses[keyof GetResponses];

export type PostEchoData = {
    body: string;
    path?: never;
    query?: never;
    url: '/echo';
};

export type PostEchoResponses = {
    200: string;
};

export type PostEchoResponse = PostEchoResponses[keyof PostEchoResponses];

export type GetUsersUserIdData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/users/:user_id';
};

export type GetUsersUserIdResponses = {
    200: User;
};

export type GetUsersUserIdResponse = GetUsersUserIdResponses[keyof GetUsersUserIdResponses];

export type PostAuthRegisterData = {
    body: RegisterUser;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterResponses = {
    200: string;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};