[package]
name = "rspc-svelte"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = "3.1.7"
poem-openapi = { version = "5.1.8", features = ["swagger-ui"] }
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
