name: Spec/Test CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      # Set up Rust
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      
      # Set up Bun
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      # Install cargo-edit
      - name: Install cargo-edit
        run: cargo install cargo-edit
      
      # Install dependencies
      - name: Install dependencies
        run: bun install
      
      # Run tests
      - name: Run tests
        run: bun run test:all
